steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/image_preview', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/image_preview']
# Deploy container image to Cloud Run
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['run', 'deploy', 'service-preview', '--image', 'gcr.io/$PROJECT_ID/image_preview', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
#images:
#- gcr.io/$PROJECT_ID/image_preview